
version: "2"
services:
  app:
    container_name: app
    build: .
    ports:      
      - "3000:3000"
    depends_on:
      - chrome-container
    volumes:
      - ./tests:/tests
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      - ./app.js:/app.js

  chrome-container:
    container_name: chrome-container
    image: selenium/standalone-chrome:3.12.0-americium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
